### PR TITLE
Keinsteins fixes

### PR DESCRIPTION
**Pull request by keinstein**
Just for your review, I provide several patches and fixes which I made (or think to have achievd) in the last weeks.

Yo are free to cherry-pick some of the patches or ask to leave some out. (e.g. the constexpr patch is more an illustration and probably not applicable to upstream JUCE).

### CODE REVIEW

**Comment by dobo365** [comment]
@keinstein Thx Tobias for your support to Roman and your contribution!
I tried just building Ctrlr in VS2019 but don't know how to do it so I'll leave it and give my energy to support you in thougths.

I'm also facing an issue (in fact 2 similar ones - maybe linked) since long that I would appreciate you guys to look at as I don't know the possible reason.
1/ when opening the same panel twice within Ctrlr 5.3.201 standalone, I'm getting all possible popups opened and this is locking Ctrlr (it is needed to kill all those popups one by one).
My panels are full of Lua code. The popups that are opening are all the calls to utils.infoWindow(), utils.openFileWindow(), utils.saveFileWindow(), utils.questionWindow(), etc...
Despite blocking the Called when value changes methods with a boolean, those popups are coming.
So, it could be something related to utils.xxx.
Could it also be that global variables are global for Ctrlr and thus for all panels opened and not only for the current panel?
I'm asking because of course, when opening two times the same panel, the global variable bPanelLoaded has been set to true by the first panel and thus this is maybe fooling the second panel.
2/ similar issue but when opening the same panel as VST on two different tracks in some DAWs. Ableton is the most sensitive.
I also get all popups when opening the first panel in ABleton (some other users don't have the issue - same Ableton, same panel).

Thx a lot for your help....Dominique

**Comment by keinstein** [comment]
@dobo365 I had only a first glance at the source code of my working branch:
Every panel has its own lua manager. And every manager owns two lua instances (I didn't figure out why these are two but it doesn't matter for your question). Neither the panel nor the lua manager seems to have any code that allows to assign an instance from outside. So sharing a lua instance should not be possible on that level. So either lua allows only one instance. In that case Ctrlr should crash more often.

Since I din't get the included Lua running. I'm using Lua 5.2 from my Linux distribution. This properly separates the Lua sessions. 

Is it possible that your panel gets access to the other panels through a backdoor via JUCE? And that this is not an issue as long as you have only one instance open. For example when you are searching for the panel control via the panel name, it might simply find the wrong panel. This is probably bug in Ctrlr, but it is hard to solve. Maybe you invented the in-Ctrlr malware?

Could you investigate the problem into this direction? Can you make a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example), please?

**Comment by dobo365** [comment]
Thx for your feedback!
I will try building a minimal panel that makes the bug appear. I can just destroy one of my panels ;-)
In fact, for the case number one, it is not when opening the same panel twice (but that as well), it is when opening different panels using similar code (I'm re-using the same structure of code in all my panels).
So, panel ID is different BUT many global variables have the same name. Many methods have the same name but different content.
This problem is annoying within Ctrlr because I want sometimes to copy/paste code from one panel to the other and is annoying as a whole in VST versions because you cannot open 2 times the same panel on different tracks EXCEPT when creating a track from some track template.
Replacing a track preset by another track preset is also creating the mess.
But, OK, you got the picture I think. Let me find this minimal working or buggy example.

**Comment by dobo365** [comment]
@keinstein OK. I have been cleaning an existing panel to only leave a few things but still have the issue.
[Popups bug panel_0_9_2021-02-24_22-49.zip](https://github.com/RomanKubiak/ctrlr/files/6039063/Popups.bug.panel_0_9_2021-02-24_22-49.zip)

Only a few popups are now generated and there is almost no code left.
When you open the first panel it is nice and you can use the different buttons (Rename, Author...).
When you open the second panel, it shows all popups. Called when mod value change is executed despite the presence of isPanelReady() that has been working for the first instance.
isPanelReady() is in the Miscellaneous method.

Shall I keep this here or start another thread?

@RomanKubiak Maybe that you will have some clue, Roman?

**Review by rkubiak01 — APPROVED** [review]

**Pull request merged**
