### PR TITLE
Keinsteins fixes

### LINKED ISSUE #167: Renaming lua functions crashes Ctrlr
Hi,

Ctrlr seems not to be fault tolerant. I came accross several situations when it simply crashed.
One situation occurs when I have typo in the function name of a lua function. When I correct the typo, the function name gets not updated in the GUI and the GUI offers no option to update the function name. Finally the GUI does not allow to select the new function name and does not complain. It simply crashes when the function is called.

### PR DESCRIPTION
**Pull request by keinstein**
I have prepared another set of fixes. Two of them (3db683d  and bf42415) hould be tested before they are released to the public.
Both may have a deeper impact on Ctrlr and the panel development.

I plan to use the it for my panel development.

3db683d fixes #167

### CODE REVIEW

**Comment by dobo365** [comment]
Thx Tobias! I identified the following bugs in 5.3.201. Can you check if they are solved or propose some fix?
Thx in advance. I wish I could do this myself...

Issue with File path refresh
To reproduce:
Modify unique panel ID
Save As new_name
File path is adapted in properties
Close panel
Open new panel
File path is still the old one!!!
So needed to do a "Save As" because otherwise, old panel is overwritten

**************************************

Clicking on a property label looks like a link but doesn't open any popup to show help explanation.

**************************************

Panel Background colour property doesn't work
Need to use Background colour [1] and set Gradient to None.

Background colour [1] is indicated 2 times and the second one should obviously be Background colour [2] 

**************************************

Deleting a tab is not deleting underlying modulators (they are all coming on Tab 0)

***************************************

Moving a tab is not changing the Tab property of the modulators

***************************************

Undo is not working after deleting a modulator?

***************************************

Un-comment functions about parent/child manipulations in https://github.com/RomanKubiak/ctrlr/blob/de28dc3ad3591a5832f1e38ce8adabc9369b1011/Source/Lua/JuceClasses/LComponents.cpp ?

Need getChildComponent() in order to modify the background image of a specific tab
console(tostring(panel:getComponent("GrandmotherTabs"):getChildComponent(0):getPropertyString("uiTabsTabIndex")))
panel:getComponent("GrandmotherTabs"):getChildComponent(0):setProperty ("uiTabsTabBackgroundImage", "Grandmother panel", false)

***************************************

Cancelling an Export as restricted instance or Export instance gives an error message
"Failed to export as a standalone instance
Windows Native: exportMeWithNewResource "Save file" dialoag failed"

***************************************

Cancelling an Export binary + resource gives an error message
"Destination file does not exist or is invalid"

***************************************

Cancelling an Export binary doesn't gives an error message but shows a red bar at bottom
"Save file dialog failed"

**Comment by keinstein** [comment]
@dobo365 it seems that none of this issues is addressed by my fixes. If you want to check them by yourself, you can click on every patch above to read its description. The patches don't change much more than the descriptions say.

And please, copy the link to the issues into your requests or answeres, so that GitHub can link  them like https://github.com/RomanKubiak/ctrlr/pull/323 (full link) or #323 (like # followed by the issue number in GitHub).

**Comment by dobo365** [comment]
OK. Are you suggesting I should post an Issue for each of them so it can later on be referred with the issue number by someone doing the fix? I think I already posted a few.
Just confirm what You'd like me to do. Thx!

**Comment by keinstein** [comment]
@dobo365 Please, be patient or buy a developer who will address your issues. If you want that people keep listening to you, keep the noise level low. Some suggestions:

- Read and try to understand the patch descriptions, you can click on each commit to open the full description
- Address your issues **always** with cross references (see below), if there is no issue so far, you could create one.
- Always discuss the topics that are opened by the original issue. In case of a pull request these are the patches that are included and the features that are implemented by them.
- Read [https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax](Basic writing and formatting syntax) and [https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue](Creating an issue) for technical help.
- Please keep track of your own issues. Whenever there is a patch or pull request that you think might solve your issue, you can copy the URL of the patch and answer your own issue with the question: „Does insert-the-copied-URL-here solve this issue?“ If the URL is recognised by GitHub, a readable link will be generated as in https://github.com/RomanKubiak/ctrlr/pull/323#issuecomment-864617256 (or here).

**Comment by nathan-stewart** [comment]
I'm still not seeing any MIDI devices with this change set even though they show up in amidi -l.

**Comment by nathan-stewart** [comment]
> I'm still not seeing any MIDI devices with this change set even though they show up in amidi -l.

Scratch that - I didn't realize that you won't see MIDI interfaces until the panel is open (which was crashing until I checkout out the keinsteins_fixes branch.

**Pull request merged**
