### PR TITLE
Kiosk

### PR DESCRIPTION
**Pull request by mus-candidus**
First of all: Thanks for Ctrlr. It's a great tool to control MIDI devices and the only one I know on Linux so far.

I made some changes to support MidiContinue, MidiStop amd MidiStart messages. Works great with my Korg minilogue.
Some changes in build.sh were necessary for OpenSUSE to detect libbfd. I hope I didn't break building on Debian-based systems.

### CODE REVIEW

**Comment by nathan-stewart** [comment]
Are there any objections to merging this?

**Comment by keinstein** [comment]
- Could you rebase your changes on master? They are not connected in any way with Kiosk mode.
- please don't edit Builds/LinuxMakefile/Makefile manually, this file is generated automatically whenever Ctrlr.jucer is changed. So the get silently overwritten. You can suggest your solution to [JUCE](https://github.com/juce-framework/JUCE/)
- commit 39d8e0e5e8460c10840f52735279e2a78267645a should be removed
- The other two commits should be based on master as they are not related to kiosk mode

**Comment by mus-candidus** [comment]
I was advised to use the Kiosk branch because I had build issues that unfortunately remained. That's why I modified the Makefile, it was the only way for me to make things work. I will rebase my Midi-related changes and open a new PR but something has to be done about the libbfd linking issue.

**Comment by keinstein** [comment]
Look at #400, please. It is already merged in the upstream+fixes branch from damiensellier/CtrlrX .

**Comment by mus-candidus** [comment]
Rebased it as requested: [434](https://github.com/RomanKubiak/ctrlr/pull/434)

**Pull request merged**
